### ISSUE TITLE
 the hidden state of the last input token outputted by the top model layer

### ISSUE THREAD

**Issue by A1pacin0** [chujiezheng/LLM-Safeguard#5]
How to extract the hidden state of the last input token outputted by the top model layer? I didn't see it in the repo. Could you please share it?

**Comment by chujiezheng** [comment]
In this step, we extract all layers' hidden states.

https://github.com/chujiezheng/LLM-Safeguard/blob/34b457ef1526c28dcc7a4a201663a5bfaa9031ee/code/forward.py#L148

In this step, we use only the top layer's hidden state.

https://github.com/chujiezheng/LLM-Safeguard/blob/34b457ef1526c28dcc7a4a201663a5bfaa9031ee/code/estimate.py#L112

In these two steps in `train.py`, we also use only the top layer's hidden state.

https://github.com/chujiezheng/LLM-Safeguard/blob/34b457ef1526c28dcc7a4a201663a5bfaa9031ee/code/train.py#L214

https://github.com/chujiezheng/LLM-Safeguard/blob/34b457ef1526c28dcc7a4a201663a5bfaa9031ee/code/train.py#L235

**Comment by A1pacin0** [comment]
Very thanks for your share! I've successfully replicated your experiment. This is a very good piece of work！

**Comment by Huahuoy** [comment]
> Very thanks for your share! I've successfully replicated your experiment. This is a very good piece of work！

Can you give a complete code execution order? If so, I will be very grateful to you.

when i run generate.py

sequence_ids: ()
Traceback (most recent call last):
File "/mnt/workspace/LLM-Safeguard-main/code/generate.py", line 384, in
main()
File "/mnt/workspace/LLM-Safeguard-main/code/generate.py", line 358, in main
for res in pool.imap(generate_fn, enumerate(zip(seeds, all_queries, all_messages)), chunksize=1):
File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 873, in next
raise value
File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/mnt/workspace/LLM-Safeguard-main/code/generate.py", line 89, in generate
generations = model.generate(
File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1520, in generate
return self.sample(
File "/usr/local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2630, in sample
next_token_scores = logits_processor(input_ids, next_token_logits)
File "/usr/local/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 97, in call
scores = processor(input_ids, scores)
File "/usr/local/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 1033, in call
last_token = sequence_ids[-1]
IndexError: tuple index out of range
