### ISSUE TITLE
code execute order

### ISSUE THREAD

**Issue by Huahuoy** [chujiezheng/LLM-Safeguard#9]
Can you give a complete code execution order? If so, I will be very grateful to you.

**Comment by Huahuoy** [comment]
when i run generate.py 

sequence_ids: ()
Traceback (most recent call last):
  File "/mnt/workspace/LLM-Safeguard-main/code/generate.py", line 384, in <module>
    main()
  File "/mnt/workspace/LLM-Safeguard-main/code/generate.py", line 358, in main
    for res in pool.imap(generate_fn, enumerate(zip(seeds, all_queries, all_messages)), chunksize=1):
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/mnt/workspace/LLM-Safeguard-main/code/generate.py", line 89, in generate
    generations = model.generate(
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1520, in generate
    return self.sample(
  File "/usr/local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2630, in sample
    next_token_scores = logits_processor(input_ids, next_token_logits)
  File "/usr/local/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 97, in __call__
    scores = processor(input_ids, scores)
  File "/usr/local/lib/python3.10/site-packages/transformers/generation/logits_process.py", line 1033, in __call__
    last_token = sequence_ids[-1]
IndexError: tuple index out of range
